### PR TITLE
Use anchors when linking to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by betatim**
This is a Pull Request (PR) 😄 

Following on from the discussion in #1 I edited the README to link to the subsections of `CONTRIBUTING.md`. Let me know what you think and I can make some more changes/edits.

### CODE REVIEW

**Comment by RaoOfPhysics** [comment]
NOOOOO, @betatim! I was working on this as I said in #1. :P 

Oh, well.

(**EDIT**: https://github.com/RaoOfPhysics/fig-can/tree/update-readme for completeness.)

@j-joe-akin: I think you should merge @betatim's PR since he was faster than I was. :)

**Comment by j-joe-akin** [comment]
Thanks @betatim and @RaoOfPhysics! I will close #1

**Comment by betatim** [comment]
Oups, sorry @RaoOfPhysics somehow I parsed that conversation as "this is how you could do it if you wanted to".

**Comment by RaoOfPhysics** [comment]
No problem at all, @betatim. :)

**Pull request merged**
